### ISSUE TITLE
Copy style of About window from QTiles

### ISSUE THREAD

**Issue by simgislab** [nextgis/dtclassifier#12]
Raster classification using decision trees.

This plugin allows to selected areas of interest (presence) and areas of no interest (absence) and then classifies raster data using collected training data to find more of areas of interest.

Developers: NextGIS
Homepage: https://github.com/nextgis/dtlclassifier
Please report bugs at bugtracker

**Comment by alisovenko** [comment]
Homepage: https://github.com/nextgis/dtclassifier

bugtracker это ссылка на https://github.com/nextgis/dtclassifier/issues
так?

**Comment by simgislab** [comment]
так точно

**Comment by alisovenko** [comment]
Done
