### ISSUE TITLE
new icon

### ISSUE THREAD

**Issue by simgislab** [nextgis/dtclassifier#2]

**Comment by simgislab** [comment]
may be this: https://thenounproject.com/search/?q=classification&i=152829

**Comment by alisovenko** [comment]
I like something similar to:
https://thenounproject.com/term/venn-diagram/167349/ (best for me)
https://thenounproject.com/term/venn-diagram/177502/
https://thenounproject.com/term/light-and-dark/94012/
https://thenounproject.com/term/social-network/25481/

**Comment by simgislab** [comment]
3!
